targets:
  $default:
    builders:
      hive_generator|hive_generator:
        generate_for:
          - lib/**.dart
      source_gen|combining_builder:
        generate_for:
          - lib/**.dart
