name: invoice_lite
description: "A lightweight invoicing application for small businesses"

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.13.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.1
  
  # UI Components
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10+1
  search_choices: ^2.3.1
  flutter_typeahead: ^5.1.2
  cupertino_icons: ^1.0.8
  flutter_slidable: ^4.0.0
  shimmer: ^3.0.0
  
  # Database
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.16
  sqlite3: ^2.5.0
  path_provider: ^2.1.2
  path: ^1.8.3
  shared_preferences: ^2.2.3
  
  # Form Handling - Using custom validation
  
  # PDF Generation & Sharing
  pdf: ^3.10.7
  share_plus: ^7.2.1
  url_launcher: ^6.2.5
  
  # Charts
  syncfusion_flutter_charts: ^24.1.50
  
  # Immutable Models & Serialization
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  
  # Dependency Injection
  injectable: ^2.1.5
  get_it: ^7.6.7
  
  # Utilities
  intl: ^0.18.1  # Required by syncfusion_flutter_charts and compatible with form_builder_validators 9.1.0
  uuid: ^4.3.3
  equatable: ^2.0.5
  collection: ^1.18.0
  logger: ^2.1.0
  phone_numbers_parser: ^9.0.3
  email_validator: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.8
  drift_dev: ^2.14.0
  freezed_annotation: ^2.4.1
  json_serializable: ^6.9.4
  
  # Static Analysis
  flutter_lints: ^5.0.0
  
  # Testing
  mockito: ^5.4.4
  mocktail: ^1.0.4
  test: ^1.24.8

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
